INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_SPACEGRANT spacegrant)

FIND_PATH(
    SPACEGRANT_INCLUDE_DIRS
    NAMES spacegrant/api.h
    HINTS $ENV{SPACEGRANT_DIR}/include
        ${PC_SPACEGRANT_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    SPACEGRANT_LIBRARIES
    NAMES gnuradio-spacegrant
    HINTS $ENV{SPACEGRANT_DIR}/lib
        ${PC_SPACEGRANT_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SPACEGRANT DEFAULT_MSG SPACEGRANT_LIBRARIES SPACEGRANT_INCLUDE_DIRS)
MARK_AS_ADVANCED(SPACEGRANT_LIBRARIES SPACEGRANT_INCLUDE_DIRS)

